#!/usr/bin/env bash
# Upload data/accordi.db to Turso and build the FTS search index.
# Requires: turso CLI (https://docs.turso.tech/cli), logged in via `turso auth login`
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_FILE="${DB_FILE:-$ROOT/data/accordi.db}"
DB_NAME="${DB_NAME:-strimpello}"

export PATH="${PATH:+$PATH:}${HOME}/.turso"

if ! command -v turso >/dev/null 2>&1; then
  echo "Turso CLI not found. Install: curl -sSfL https://get.tur.so/install.sh | bash"
  exit 1
fi

if ! turso auth whoami >/dev/null 2>&1; then
  echo "Not logged in. Run: turso auth login"
  exit 1
fi

if [[ ! -f "$DB_FILE" ]]; then
  echo "Missing database: $DB_FILE"
  echo "Run the crawler first (see README.md)."
  exit 1
fi

echo "==> Turso account: $(turso auth whoami)"

if ! turso db show "$DB_NAME" >/dev/null 2>&1; then
  echo "==> Creating database: $DB_NAME"
  turso db create "$DB_NAME"
else
  echo "==> Database exists: $DB_NAME"
fi

echo "==> Preparing SQLite file (WAL mode required by Turso)..."
TMP_DB="$(mktemp /tmp/strimpello-XXXXXX.db)"
cp "$DB_FILE" "$TMP_DB"
sqlite3 "$TMP_DB" "PRAGMA journal_mode=WAL; PRAGMA wal_checkpoint(truncate);"

echo "==> Importing $(du -h "$TMP_DB" | cut -f1) (this may take several minutes)..."
if turso db import "$TMP_DB" 2>/dev/null; then
  IMPORTED_NAME="$(basename "$TMP_DB" .db)"
  if [[ "$IMPORTED_NAME" != "$DB_NAME" ]]; then
    echo "    Imported as '$IMPORTED_NAME' (Turso names db after the file)."
    DB_NAME="$IMPORTED_NAME"
  fi
else
  echo "    CLI import failed — trying Platform API upload..."
  PLATFORM_TOKEN="$(turso auth api-tokens mint deploy-"$DB_NAME" 2>&1 | tail -1)"
  ORG_SLUG="$(turso org list 2>/dev/null | awk '/current/{print $2}' | tr -d '()')"
  curl -sf -X POST "https://api.turso.tech/v1/organizations/${ORG_SLUG}/databases" \
    -H "Authorization: Bearer ${PLATFORM_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "{\"name\":\"${DB_NAME}\",\"group\":\"default\",\"seed\":{\"type\":\"database_upload\"}}" >/dev/null || true
  DB_TOKEN="$(curl -sf -X POST "https://api.turso.tech/v1/organizations/${ORG_SLUG}/databases/${DB_NAME}/auth/tokens" \
    -H "Authorization: Bearer ${PLATFORM_TOKEN}" | python3 -c "import sys,json; print(json.load(sys.stdin)['jwt'])")"
  HOST="$(turso db show "$DB_NAME" 2>/dev/null | awk '/^URL:/{print $2}' | sed 's|libsql://||')"
  curl -sf -X POST "https://${HOST}/v1/upload" \
    -H "Authorization: Bearer ${DB_TOKEN}" \
    --data-binary @"$TMP_DB"
fi
rm -f "$TMP_DB"

echo "==> Creating auth token..."
TOKEN="$(turso db tokens create "$DB_NAME" 2>&1 | tail -1)"
URL="$(turso db show "$DB_NAME" --url)"
# Regional hostname may not resolve immediately; the global host always works.
URL="${URL/aws-eu-west-1.turso.io/turso.io}"
URL="${URL/aws-us-east-1.turso.io/turso.io}"

echo "==> Building search index on Turso..."
cd "$ROOT/web"
TURSO_DATABASE_URL="$URL" TURSO_AUTH_TOKEN="$TOKEN" npm run build:search-index

ENV_FILE="$ROOT/web/.env.local"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy-turso.sh — do not commit
TURSO_DATABASE_URL=$URL
TURSO_AUTH_TOKEN=$TOKEN
NEXT_PUBLIC_SITE_URL=http://localhost:3000
EOF

echo ""
echo "Done."
echo ""
echo "Local env written to: web/.env.local"
echo ""
echo "Add these to Vercel (Project → Settings → Environment Variables):"
echo "  TURSO_DATABASE_URL=$URL"
echo "  TURSO_AUTH_TOKEN=<see web/.env.local>"
echo "  NEXT_PUBLIC_SITE_URL=https://your-domain.vercel.app"
echo ""
echo "Turso dashboard: turso db show $DB_NAME"
